#Application Properties
application:
    storage:
        type: ${STORAGE_TYPE}
        filesystem:
            path: D:/TMP/
            max-file-size: 1MB
        metadata:
            path: D:/TMP/

#Spring Properties
spring:
    output:
        ansi:
            enabled: always
    mvc:
        favicon:
            enabled: false
        servlet:
            load-on-startup: 1
    http:
        multipart:
            max-file-size: ${application.storage.filesystem.max-file-size}
    jackson:
        default-property-inclusion: non_null